-- +goose Up
-- +goose StatementBegin

INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('16395f06-0a83-11ee-b7d2-2f4bd168d74e', 'Ethereum Mainnet', 'ETH', 'mainnet', '["https://mainnet.infura.io/v3/${INFURA_API_KEY}", "wss://mainnet.infura.io/ws/v3/${INFURA_API_KEY}", "https://api.mycryptoapi.com/eth", "https://cloudflare-eth.com"]', '[]', '{"name": "Ether", "symbol": "ETH", "decimals": 18}', 'https://ethereum.org', 'eth', 1, 1, 60, '{"registry": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}', now(), null, now());
INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('167dca60-0a83-11ee-b7d2-2f4bd168d74e', 'Binance Smart Chain Mainnet', 'BSC', 'mainnet', '["https://bsc-dataseed1.binance.org", "https://bsc-dataseed2.binance.org", "https://bsc-dataseed3.binance.org", "https://bsc-dataseed4.binance.org", "https://bsc-dataseed1.defibit.io", "https://bsc-dataseed2.defibit.io", "https://bsc-dataseed3.defibit.io", "https://bsc-dataseed4.defibit.io", "https://bsc-dataseed1.ninicoin.io", "https://bsc-dataseed2.ninicoin.io", "https://bsc-dataseed3.ninicoin.io", "https://bsc-dataseed4.ninicoin.io", "wss://bsc-ws-node.nariox.org"]', '[]', '{"name": "Binance Chain Native Token", "symbol": "BNB", "decimals": 18}', 'https://www.binance.org', 'bnb', 56, 56, null, null, now(), null, now());
INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('208c7c5e-0a83-11ee-b7d2-2f4bd168d74e', 'Matic Mainnet', 'Matic', 'mainnet', '["https://rpc-mainnet.matic.network", "wss://ws-mainnet.matic.network"]', '[]', '{"name": "Matic", "symbol": "MATIC", "decimals": 18}', 'https://matic.network/', 'matic', 137, 137, null, null, now(), null, now());
INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('2b3160d4-0a83-11ee-b7d2-2f4bd168d74e', 'Arbitrum One', 'ETH', '', '["https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}", "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}", "https://arb1.arbitrum.io/rpc", "wss://arb1.arbitrum.io/ws"]', '[]', '{"name": "Ether", "symbol": "AETH", "decimals": 18}', 'https://arbitrum.io', 'arb1', 42161, 42161, null, null, now(), null, now());
INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('2bc1e67c-0a83-11ee-b7d2-2f4bd168d74e', 'Avalanche Mainnet', 'AVAX', '', '["https://api.avax.network/ext/bc/C/rpc"]', '["https://free-online-app.com/faucet-for-eth-evm-chains/"]', '{"name": "Avalanche", "symbol": "AVAX", "decimals": 18}', 'https://www.avax.network/', 'Avalanche', 43114, 43114, null, null, now(), null, now());
INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('4f699074-1280-11ef-b109-476ea78f5c06', 'Base', 'Base', 'mainnet', '["https://mainnet.base.org"]', null, '{"name": "ETH", "symbol": "ETH", "decimals": 18}', 'https://www.base.org/', 'base', 8453, 8453, null, null, now(), null, now());
INSERT INTO blockchain (id, name, chain, network, rpc, faucets, native_currency, info_url, short_name, chain_id, network_id, slip44, ens, created_at, deleted_at, updated_at) VALUES ('aa1c5300-9664-11ef-acb9-01124c8a3894', 'Soneium', 'Soneium', 'mainnet', '["https://explorer.soneium.org"]', null, '{"name": "ETH", "symbol": "ETH", "decimals": 18}', 'https://explorer.soneium.org/', 'soneium', 1868, 1868, null, null, now(), null, now());

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DELETE FROM blockchain WHERE id IN ('16395f06-0a83-11ee-b7d2-2f4bd168d74e', '167dca60-0a83-11ee-b7d2-2f4bd168d74e', '208c7c5e-0a83-11ee-b7d2-2f4bd168d74e', '2b3160d4-0a83-11ee-b7d2-2f4bd168d74e', '2bc1e67c-0a83-11ee-b7d2-2f4bd168d74e', '4f699074-1280-11ef-b109-476ea78f5c06', 'aa1c5300-9664-11ef-acb9-01124c8a3894');

-- +goose StatementEnd