/**
    * Welcome to Cloudflare Workers! This is your first worker.
    *
    * - Run "npm run dev" in your terminal to start a development server
    * - Open a browser tab at http://localhost:8787/ to see your worker in action
    * - Run "npm run deploy" to publish your worker
    *
    * Learn more at https://developers.cloudflare.com/workers/
    */

    addEventListener('fetch', event => {
      event.respondWith(handleRequest(event.request))
    })

    async function handleRequest(request) {
      const url = new URL(request.url)

      // 定义所有允许的固定路由
      const allowedRoutes = [
  "/api/doc/swagger-ui-init.js",
  "/api/doc/doc/swagger-ui-init.js",
  "/api/doc",
  "/api/doc/",
  "/api/doc-json",
  "/api/doc-yaml",
  "/*",
  "/",
  "/api/v3",
  "/health",
  "/api/v3/auth/debug/jwt-preset/get",
  "/api/v3/auth/challenge/get",
  "/api/v3/auth/email/send",
  "/api/v3/auth/email/available",
  "/api/v3/auth/username/available",
  "/api/v3/auth/wallets/available",
  "/api/v3/auth/web3/sign-up/private",
  "/api/v3/auth/web3/sign-up",
  "/api/v3/auth/web3/sign-up-torus",
  "/api/v3/auth/web3/sign-up-privy",
  "/api/v3/auth/web3/sign-in",
  "/api/v3/auth/web3/sign-in/privy",
  "/api/v3/auth/web3/sign-out",
  "/api/v3/auth/accounts/me",
  "/api/v3/auth/web3/wallets/is-bound",
  "/api/v3/auth/web3/new-wallet-sign-in",
  "/api/v3/auth/web3/new-wallet-sign-in-torus",
  "/api/v3/auth/web3/new-wallet-sign-in-privy",
  "/api/v3/auth/privy/verify",
  "/api/v3/auth/privy/user",
  "/api/v3/auth/privy/is-bound",
  "/api/v3/auth/privy/sync/wallets",
  "/api/v3/auth/social-connect",
  "/api/v3/auth/discord",
  "/api/v3/auth/discord/auth",
  "/api/v3/auth/discord/callback",
  "/api/v3/auth/twitter",
  "/api/v3/auth/twitter/callback",
  "/api/v3/auth/twitter/revoke",
  "/api/v3/auth/pregenerate-sa-address",
  "/api/v3/auth/ip",
  "/api/v3/auth/challenge/get/plus",
  "/api/v3/auth/challenge/verify/plus",
  "/api/v3/hmac-test/sign-in",
  "/api/v3/hmac-test/sign-in-encryption",
  "/api/v3/hmac-test/encrypt-data",
  "/api/v3/accounts/avatar",
  "/api/v3/accounts/profile",
  "/api/v3/accounts/referral",
  "/api/v3/accounts/referral/status",
  "/api/v3/accounts/referrer",
  "/api/v3/accounts",
  "/api/v3/accounts/username",
  "/api/v3/accounts/list/by-asset",
  "/api/v3/accounts/following/accounts",
  "/api/v3/accounts/follower/accounts",
  "/api/v3/accounts/featured/assets",
  "/api/v3/accounts/onchain-stats/wallet/summary",
  "/api/v3/assets",
  "/api/v3/assets/syncCollection",
  "/api/v3/assets/fetch",
  "/api/v3/assets/me",
  "/api/v3/assets/count",
  "/api/v3/assets/sync",
  "/api/v3/assets/user/holding",
  "/api/v3/assets/holding/soneium-badge",
  "/api/v3/traits",
  "/api/v3/traits/account-owned",
  "/api/v3/collections/upload-banner",
  "/api/v3/collections/upload-logo",
  "/api/v3/collections/upload-featured-image",
  "/api/v3/collections/upload-featured-video",
  "/api/v3/collections",
  "/api/v3/collections/order/floor-price",
  "/api/v3/collections/trading-board",
  "/api/v3/collections/me",
  "/api/v3/collections/in-management",
  "/api/v3/collections/personal",
  "/api/v3/collections/by-collection-slugs",
  "/api/v3/contracts/clean-repeat",
  "/api/v3/currency/all-pairs",
  "/api/v3/currency/history",
  "/api/v3/currency/test",
  "/api/v3/explore/assets_old",
  "/api/v3/explore/users",
  "/api/v3/explore/collections",
  "/api/v3/explore/assets",
  "/api/v3/explore/assets/test",
  "/api/v3/explore/assets/simple",
  "/api/v3/explore/assets-by-daily",
  "/api/v3/orders",
  "/api/v3/orders/bulk",
  "/api/v3/orders/history",
  "/api/v3/orders/account/received-offer",
  "/api/v3/orders/sync",
  "/api/v3/orders/event-poller/status",
  "/api/v3/orders/certification",
  "/api/v3/orders/collection-offer",
  "/api/v3/orders/disable",
  "/api/v3/orders/best-listing",
  "/api/v3/orders/platform-fee",
  "/api/v3/wallets/history",
  "/api/v3/wallets/current",
  "/api/v3/aggregator/status",
  "/api/v3/aggregator/syncOrder",
  "/api/v3/aggregator/os/signatures",
  "/api/v3/aggregator/os/collection-nfts",
  "/api/v3/aggregator/os/reload-slug",
  "/api/v3/aggregator/os/remove-slug",
  "/api/v3/aggregator/os/rpc-stats",
  "/api/v3/aggregator/os/rpc-stats-clean",
  "/api/v3/accounts-gp/payment-cost",
  "/api/v3/accounts-gp/payment-cost-invert",
  "/api/v3/accounts-gp/payment-multi-signature",
  "/api/v3/accounts-gp/balance-cost",
  "/api/v3/accounts-gp/paymaster-checker",
  "/api/v3/accounts-gp/paymaster-checker-plus",
  "/api/v3/accounts-gp/balance",
  "/api/v3/accounts-gp/history",
  "/api/v3/accounts-gp/quest/status-daily",
  "/api/v3/accounts-gp/quest/status-one-off",
  "/api/v3/accounts-gp/quest/status-trade",
  "/api/v3/accounts-gp/quest/status-recommend",
  "/api/v3/accounts-gp/quest/status-reward",
  "/api/v3/accounts-gp/quest/status-collection",
  "/api/v3/accounts-gp/referral-stats",
  "/api/v3/accounts-gp/reward/cal-tx-reward",
  "/api/v3/accounts-admin-gp/stats/account-balance",
  "/api/v3/accounts-admin-gp/history/topup-detail",
  "/api/v3/accounts-admin-gp/stats/over-balance",
  "/api/v3/accounts-admin-gp/stats/over-change",
  "/api/v3/accounts-admin-gp/refund-tx-gp",
  "/api/v3/studio/upload/presigned-url",
  "/api/v3/studio/upload/presigned-logo-url",
  "/api/v3/studio/upload/contracts/upload-logo",
  "/api/v3/studio/upload/contracts/blind-box-image",
  "/api/v3/studio/upload/contract-item/callback",
  "/api/v3/studio/upload/contracts/upload-drop-image",
  "/api/v3/studio/contracts",
  "/api/v3/studio/contracts/simple",
  "/api/v3/studio/contracts/launchpad",
  "/api/v3/studio/contracts/mint",
  "/api/v3/studio/contracts/blindbox",
  "/api/v3/studio/contracts/blindbox/count",
  "/api/v3/studio/contracts/launchpad/current",
  "/api/v3/studio/contracts/launchpad/past",
  "/api/v3/studio/contracts/reveal/challenge",
  "/api/v3/studio/contracts/reveal/verify"
];



      // 定义包含变量的路由的正则表达式
      const variableRoutes = [
  /^\/api\/v3\/auth\/web3\/wallets\/[^\/]+\/unbind$/,
  /^\/api\/v3\/auth\/accounts\/[^\/]+\/wallets$/,
  /^\/api\/v3\/auth\/referral\/is-exists\/[^\/]+$/,
  /^\/api\/v3\/auth\/social-disconnect\/[^\/]+$/,
  /^\/api\/v3\/accounts\/[^\/]+$/,
  /^\/api\/v3\/accounts\/follow\/account\/[^\/]+$/,
  /^\/api\/v3\/accounts\/featured\/assets\/[^\/]+$/,
  /^\/api\/v3\/accounts\/featured\/assets\/sync\/[^\/]+$/,
  /^\/api\/v3\/assets\/test\/[^\/]+\/[^\/]+\/[^\/]+$/,
  /^\/api\/v3\/assets\/[^\/]+$/,
  /^\/api\/v3\/assets\/username\/[^\/]+$/,
  /^\/api\/v3\/assets\/[^\/]+\/[^\/]+\/sync$/,
  /^\/api\/v3\/assets\/[^\/]+\/[^\/]+\/[^\/]+\/sync$/,
  /^\/api\/v3\/assets\/[^\/]+\/[^\/]+\/[^\/]+$/,
  /^\/api\/v3\/collections\/[^\/]+$/,
  /^\/api\/v3\/collections\/[^\/]+\/is-verified$/,
  /^\/api\/v3\/collections\/[^\/]+\/sync\/stats$/,
  /^\/api\/v3\/collections\/[^\/]+\/simple$/,
  /^\/api\/v3\/collections\/[^\/]+\/all-assets$/,
  /^\/api\/v3\/collections\/[^\/]+\/owner$/,
  /^\/api\/v3\/collections\/[^\/]+\/traits$/,
  /^\/api\/v3\/collections\/[^\/]+\/drop$/,
  /^\/api\/v3\/contracts\/[^\/]+\/[^\/]+$/,
  /^\/api\/v3\/contracts\/[^\/]+\/all-assets$/,
  /^\/api\/v3\/currency\/pair\/[^\/]+$/,
  /^\/api\/v3\/orders\/sync\/[^\/]+\/[^\/]+$/,
  /^\/api\/v3\/wallets\/record\/[^\/]+\/[^\/]+$/,
  /^\/api\/v3\/wallets\/[^\/]+$/,
  /^\/api\/v3\/wallets\/[^\/]+$/,
  /^\/api\/v3\/accounts-gp\/quest\/[^\/]+\/claim$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/status$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/template$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/item$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/upload-csv$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/update-item$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/delete-item$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/sync-ipfs$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/sync-tokenUri$/,
  /^\/api\/v3\/studio\/upload\/contracts\/[^\/]+\/blind-box\/sync-ipfs$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/blind-box$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/drop$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/drop\/visibility$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/drop\/[^\/]+$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/deploy$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/sync-status$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/post-publish$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/sales-overview$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/whitelist-check$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/launchpad$/,
  /^\/api\/v3\/studio\/contracts\/[^\/]+\/[^\/]+$/
];


      // 检查请求的路径是否在允许的固定路由列表中
      if (allowedRoutes.includes(url.pathname) || variableRoutes.some(route => route.test(url.pathname))) {
        // 如果路径在允许的固定路由列表中，或匹配任一变量路由，转发请求
        return fetch(request)
      } else {
        // 如果路径不在允许的路由列表中，返回 404
        return new Response('Not Found', { status: 404 })
      }
    }
    